//! Durable, provider-neutral Plan workflow types and state reduction.
//!
//! The transcript is the only authority for this state. Frontends receive
//! snapshots of [`PlanWorkflowState`] and send version-checked decisions; they
//! never infer workflow state from assistant prose.

use std::fmt;

use rig_core::message::Message;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{AgentRunId, EnsembleRunId, TurnId, WorkerPlanRevision};

/// The production ceiling for a canonical Plan artifact.
pub const MAX_PLAN_ARTIFACT_BYTES: usize = 128 * 1024;

/// Stable identity of one planning thread.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PlanId(Uuid);

impl PlanId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    pub const fn from_uuid(id: Uuid) -> Self {
        Self(id)
    }

    pub const fn as_uuid(self) -> Uuid {
        self.0
    }
}

impl Default for PlanId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for PlanId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Optimistic-concurrency token for a submitted Plan artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PlanVersion {
    pub id: PlanId,
    pub revision: u32,
}

impl fmt::Display for PlanVersion {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}@{}", self.id, self.revision)
    }
}

/// Complete artifact produced by `submit_plan` or explicit worker publication.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanArtifact {
    pub version: PlanVersion,
    pub title: String,
    pub markdown: String,
    pub source_turn_id: TurnId,
}

/// Terminal disposition of a planning thread.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanResolution {
    ImplementedCurrent,
    ImplementedFresh,
    /// A direct Build submission while still planning ends the thread without
    /// manufacturing an artifact.
    Abandoned,
}

/// Engine-owned workflow snapshot exposed to frontends.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(tag = "state", rename_all = "snake_case")]
pub enum PlanWorkflowState {
    #[default]
    Idle,
    Planning {
        id: PlanId,
        previous: Option<PlanArtifact>,
    },
    Ready {
        artifact: PlanArtifact,
    },
    Published {
        artifact: PlanArtifact,
    },
    Resolved {
        artifact: PlanArtifact,
        resolution: PlanResolution,
    },
}

impl PlanWorkflowState {
    pub fn artifact(&self) -> Option<&PlanArtifact> {
        match self {
            Self::Planning { previous, .. } => previous.as_ref(),
            Self::Ready { artifact }
            | Self::Published { artifact }
            | Self::Resolved { artifact, .. } => Some(artifact),
            Self::Idle => None,
        }
    }

    pub fn version(&self) -> Option<PlanVersion> {
        self.artifact().map(|artifact| artifact.version)
    }
}

/// User choice for a submitted artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanDecision {
    Revise,
    ImplementCurrent,
    ImplementFresh,
}

/// Typed, self-contained Build handoff. `prompt` is generated by the engine
/// and is the only part projected into model history.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlanHandoff {
    pub artifact: PlanArtifact,
    pub source_session_id: String,
    pub prompt: Message,
}

impl PlanHandoff {
    pub fn new(artifact: PlanArtifact, source_session_id: impl Into<String>) -> Self {
        let source_session_id = source_session_id.into();
        let prompt = Message::user(format!(
            "Implement the approved plan below. Treat it as the implementation specification.\n\n\
             Plan version: {}\nSource session: {}\n\n{}",
            artifact.version, source_session_id, artifact.markdown
        ));
        Self {
            artifact,
            source_session_id,
            prompt,
        }
    }

    pub fn is_canonical(&self) -> bool {
        Self::new(self.artifact.clone(), self.source_session_id.clone()).prompt == self.prompt
    }
}

/// Validated but not yet committed candidate carried through `ToolContext`.
/// Fields are private so only the fixed validator can construct one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlanCandidate {
    title: String,
    markdown: String,
}

impl PlanCandidate {
    pub fn validate(
        title: String,
        markdown: String,
        max_artifact_bytes: usize,
    ) -> Result<Self, PlanValidationError> {
        validate_title(&title)?;
        let max_artifact_bytes = max_artifact_bytes.min(MAX_PLAN_ARTIFACT_BYTES);
        if markdown.len() > max_artifact_bytes {
            return Err(PlanValidationError(format!(
                "markdown is {} bytes; the configured limit is {max_artifact_bytes} bytes",
                markdown.len()
            )));
        }
        let expected_heading = format!("# {title}");
        if markdown.lines().next() != Some(expected_heading.as_str()) {
            return Err(PlanValidationError(format!(
                "markdown must begin with exactly `{expected_heading}`"
            )));
        }
        for heading in ["Goal", "Decisions", "Implementation", "Validation", "Risks"] {
            validate_nonempty_section(&markdown, heading)?;
        }
        Ok(Self { title, markdown })
    }

    pub fn title(&self) -> &str {
        &self.title
    }

    pub fn markdown(&self) -> &str {
        &self.markdown
    }

    pub fn into_artifact(self, version: PlanVersion, source_turn_id: TurnId) -> PlanArtifact {
        PlanArtifact {
            version,
            title: self.title,
            markdown: self.markdown,
            source_turn_id,
        }
    }
}

/// Formatting-relaxed artifact for a host-confirmed worker publication only.
/// This is deliberately not a `PlanCandidate`: it cannot pass `submit_plan`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DirectWorkerPlan {
    title: String,
    markdown: String,
}

impl DirectWorkerPlan {
    pub fn validate(markdown: String) -> Result<Self, PlanValidationError> {
        if markdown.trim().is_empty() {
            return Err(PlanValidationError(
                "confirmed worker plan Markdown must not be empty".into(),
            ));
        }
        if markdown.len() > MAX_PLAN_ARTIFACT_BYTES {
            return Err(PlanValidationError(format!(
                "confirmed worker plan is {} bytes; the final artifact limit is {MAX_PLAN_ARTIFACT_BYTES} bytes; send worker feedback to shorten the plan before confirming (it will not be truncated)",
                markdown.len()
            )));
        }
        let title = worker_plan_title(&markdown).unwrap_or_else(|| "Confirmed worker plan".into());
        Ok(Self { title, markdown })
    }

    pub fn into_artifact(self, version: PlanVersion, source_turn_id: TurnId) -> PlanArtifact {
        PlanArtifact {
            version,
            title: self.title,
            markdown: self.markdown,
            source_turn_id,
        }
    }
}

/// Parse metadata only; never render the parser output back into the artifact.
fn worker_plan_title(markdown: &str) -> Option<String> {
    use pulldown_cmark::{Event, HeadingLevel, Parser, Tag, TagEnd};
    let mut heading = None::<String>;
    for event in Parser::new(markdown) {
        match event {
            Event::Start(Tag::Heading {
                level: HeadingLevel::H1,
                ..
            }) => heading = Some(String::new()),
            Event::End(TagEnd::Heading(HeadingLevel::H1)) => {
                let title = heading.take().unwrap_or_default();
                let title = title.split_whitespace().collect::<Vec<_>>().join(" ");
                if !title.is_empty() {
                    return Some(title);
                }
            }
            Event::Text(text) | Event::Code(text) if heading.is_some() => {
                heading.as_mut().unwrap().push_str(&text)
            }
            Event::SoftBreak | Event::HardBreak if heading.is_some() => {
                heading.as_mut().unwrap().push(' ')
            }
            _ => {}
        }
    }
    None
}

/// Only the explicitly tagged, cross-record-verified worker source permits
/// noncanonical Markdown. Synthesized publication remains strictly validated.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "source", rename_all = "snake_case", deny_unknown_fields)]
pub enum PlanPublicationProvenance {
    Synthesized,
    ConfirmedWorker {
        run_id: EnsembleRunId,
        worker_id: AgentRunId,
        revision: WorkerPlanRevision,
    },
}

fn validate_title(title: &str) -> Result<(), PlanValidationError> {
    if title.trim() != title || title.lines().count() != 1 {
        return Err(PlanValidationError(
            "title must be one line with no leading or trailing whitespace".to_string(),
        ));
    }
    let words = title.split_whitespace().count();
    if !(3..=8).contains(&words) {
        return Err(PlanValidationError(
            "title must contain 3–8 words".to_string(),
        ));
    }
    Ok(())
}

fn validate_nonempty_section(markdown: &str, heading: &str) -> Result<(), PlanValidationError> {
    let marker = format!("## {heading}");
    let mut lines = markdown.lines();
    let Some(_) = lines.find(|line| *line == marker) else {
        return Err(PlanValidationError(format!(
            "markdown is missing the required `{marker}` section"
        )));
    };
    let nonempty = lines
        .take_while(|line| !line.starts_with("## "))
        .any(|line| !line.trim().is_empty());
    if !nonempty {
        return Err(PlanValidationError(format!(
            "the `{marker}` section must not be empty"
        )));
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlanValidationError(String);

impl fmt::Display for PlanValidationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl std::error::Error for PlanValidationError {}

/// Typed workflow records embedded in the JSONL transcript.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum PlanRecord {
    Started {
        id: PlanId,
    },
    Ready {
        artifact: PlanArtifact,
    },
    Published {
        artifact: PlanArtifact,
        provenance: PlanPublicationProvenance,
    },
    RevisionRequested {
        artifact: PlanArtifact,
    },
    Resolved {
        id: PlanId,
        artifact: Option<PlanArtifact>,
        resolution: PlanResolution,
    },
    Handoff {
        handoff: PlanHandoff,
    },
}

impl PlanRecord {
    /// The handoff prompt is the sole workflow record visible to a model.
    pub fn model_message(&self) -> Option<&Message> {
        match self {
            Self::Handoff { handoff } => Some(&handoff.prompt),
            Self::Started { .. }
            | Self::Ready { .. }
            | Self::Published { .. }
            | Self::RevisionRequested { .. }
            | Self::Resolved { .. } => None,
        }
    }
}

/// Reconstruct workflow state by replaying typed records in transcript order.
pub fn replay_plan_state<'a>(
    records: impl IntoIterator<Item = &'a PlanRecord>,
) -> anyhow::Result<PlanWorkflowState> {
    let mut state = PlanWorkflowState::Idle;
    for record in records {
        state = apply_plan_record(state, record)?;
    }
    Ok(state)
}

/// Apply one durable workflow record to an already-replayed prefix state.
///
/// Session edits use this reducer after replaying their retained prefix so a
/// prepared transition is validated exactly once before the transcript commit.
pub fn apply_plan_record(
    state: PlanWorkflowState,
    record: &PlanRecord,
) -> anyhow::Result<PlanWorkflowState> {
    match record {
        PlanRecord::Started { id } => match state {
            PlanWorkflowState::Idle
            | PlanWorkflowState::Published { .. }
            | PlanWorkflowState::Resolved { .. } => Ok(PlanWorkflowState::Planning {
                id: *id,
                previous: None,
            }),
            PlanWorkflowState::Planning { .. } | PlanWorkflowState::Ready { .. } => {
                anyhow::bail!("Plan Started record does not follow Idle or Resolved state")
            }
        },
        PlanRecord::Ready { artifact } | PlanRecord::Published { artifact, .. } => {
            let PlanWorkflowState::Planning { id, previous } = &state else {
                anyhow::bail!("Plan Ready record does not follow Planning state");
            };
            if *id != artifact.version.id {
                anyhow::bail!("Plan Ready record changes the active plan id");
            }
            let expected_revision = previous
                .as_ref()
                .map_or(1, |previous| previous.version.revision.saturating_add(1));
            if artifact.version.revision != expected_revision {
                anyhow::bail!(
                    "Plan Ready revision {} does not follow expected revision {expected_revision}",
                    artifact.version.revision
                );
            }
            if let PlanRecord::Published {
                provenance: PlanPublicationProvenance::ConfirmedWorker { .. },
                ..
            } = record
            {
                let direct = DirectWorkerPlan::validate(artifact.markdown.clone())?;
                anyhow::ensure!(
                    artifact.title == direct.title,
                    "direct worker publication title differs from its Markdown metadata"
                );
            } else {
                PlanCandidate::validate(
                    artifact.title.clone(),
                    artifact.markdown.clone(),
                    MAX_PLAN_ARTIFACT_BYTES,
                )?;
            }
            Ok(if matches!(record, PlanRecord::Published { .. }) {
                PlanWorkflowState::Published {
                    artifact: artifact.clone(),
                }
            } else {
                PlanWorkflowState::Ready {
                    artifact: artifact.clone(),
                }
            })
        }
        PlanRecord::RevisionRequested { artifact } => {
            let (PlanWorkflowState::Ready { artifact: ready }
            | PlanWorkflowState::Published { artifact: ready }) = &state
            else {
                anyhow::bail!("Plan revision record does not follow Ready state");
            };
            if ready != artifact {
                anyhow::bail!("Plan revision record does not match the ready artifact");
            }
            Ok(PlanWorkflowState::Planning {
                id: artifact.version.id,
                previous: Some(artifact.clone()),
            })
        }
        PlanRecord::Resolved {
            id,
            artifact,
            resolution,
        } => {
            if *resolution == PlanResolution::Abandoned {
                let PlanWorkflowState::Planning {
                    id: active,
                    previous,
                } = state
                else {
                    anyhow::bail!("Plan abandonment does not follow Planning state");
                };
                if active != *id {
                    anyhow::bail!("Plan abandonment changes the active plan id");
                }
                if &previous != artifact {
                    anyhow::bail!("Plan abandonment does not retain the previous artifact");
                }
                return Ok(PlanWorkflowState::Idle);
            }
            let artifact = artifact
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("an implementation resolution needs an artifact"))?;
            let submitted = match &state {
                PlanWorkflowState::Ready { artifact }
                | PlanWorkflowState::Published { artifact } => artifact,
                PlanWorkflowState::Planning {
                    id: active,
                    previous: Some(previous),
                } if active == id => previous,
                PlanWorkflowState::Idle
                | PlanWorkflowState::Planning { .. }
                | PlanWorkflowState::Resolved { .. } => {
                    anyhow::bail!(
                        "Plan implementation resolution does not follow Ready or retained Planning state"
                    )
                }
            };
            if submitted != artifact || artifact.version.id != *id {
                anyhow::bail!("Plan resolution does not match the submitted artifact");
            }
            Ok(PlanWorkflowState::Resolved {
                artifact: artifact.clone(),
                resolution: *resolution,
            })
        }
        PlanRecord::Handoff { .. } => Ok(state),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_markdown(title: &str) -> String {
        format!(
            "# {title}\n\n## Goal\nShip it.\n\n## Decisions\nUse Rust.\n\n\
             ## Implementation\nBuild it.\n\n## Validation\nTest it.\n\n## Risks\nNone."
        )
    }

    #[test]
    fn candidate_validation_pins_the_contract() {
        let title = "Durable plan workflow";
        PlanCandidate::validate(
            title.to_string(),
            valid_markdown(title),
            MAX_PLAN_ARTIFACT_BYTES,
        )
        .expect("valid candidate");

        for markdown in [
            valid_markdown(title).replacen("# Durable", " # Durable", 1),
            valid_markdown(title).replace("## Risks\nNone.", "## Risks\n"),
            valid_markdown(title).replace("## Goal", "## Objective"),
        ] {
            assert!(
                PlanCandidate::validate(title.to_string(), markdown, MAX_PLAN_ARTIFACT_BYTES)
                    .is_err()
            );
        }
        assert!(
            PlanCandidate::validate(
                "Too short".to_string(),
                valid_markdown("Too short"),
                MAX_PLAN_ARTIFACT_BYTES
            )
            .is_err()
        );

        let oversized = valid_markdown(title);
        let error =
            PlanCandidate::validate(title.to_string(), oversized.clone(), oversized.len() - 1)
                .expect_err("the configured byte ceiling must be enforced");
        assert!(error.to_string().contains("configured limit"));

        let above_hard_ceiling = format!(
            "{}\n{}",
            valid_markdown(title),
            "x".repeat(MAX_PLAN_ARTIFACT_BYTES)
        );
        let error = PlanCandidate::validate(title.to_string(), above_hard_ceiling, usize::MAX)
            .expect_err("callers cannot widen the fixed production ceiling");
        assert!(
            error
                .to_string()
                .contains(&MAX_PLAN_ARTIFACT_BYTES.to_string())
        );
    }

    #[test]
    fn direct_worker_validation_preserves_bytes_and_only_derives_metadata() {
        for (markdown, title) in [
            ("Do this.  ", "Confirmed worker plan"),
            ("\r\n  # Go\r\n\r\n- Ship it.  \r\n", "Go"),
            ("# Short", "Short"),
            ("#\n\nbody", "Confirmed worker plan"),
            (
                "```md\n# Not a title\n```\n\n# Actual `title` ###",
                "Actual title",
            ),
            ("Setext title\n============\nbody", "Setext title"),
        ] {
            let version = PlanVersion {
                id: PlanId::new(),
                revision: 1,
            };
            let artifact = DirectWorkerPlan::validate(markdown.into())
                .unwrap()
                .into_artifact(version, TurnId::new(1));
            assert_eq!(artifact.title, title);
            assert_eq!(artifact.markdown.as_bytes(), markdown.as_bytes());
            assert!(
                PlanCandidate::validate(title.into(), markdown.into(), MAX_PLAN_ARTIFACT_BYTES)
                    .is_err()
            );
            let handoff = PlanHandoff::new(artifact.clone(), "source");
            assert_eq!(handoff.artifact, artifact);
            assert!(handoff.is_canonical());
        }
        for markdown in [
            "".to_string(),
            " \r\n\t".into(),
            "x".repeat(MAX_PLAN_ARTIFACT_BYTES + 1),
        ] {
            assert!(DirectWorkerPlan::validate(markdown).is_err());
        }
        assert!(DirectWorkerPlan::validate("x".repeat(MAX_PLAN_ARTIFACT_BYTES)).is_ok());
    }

    #[test]
    fn relaxed_plan_replay_requires_explicit_direct_provenance() {
        let id = PlanId::new();
        let artifact = DirectWorkerPlan::validate("Just implement this.  ".into())
            .unwrap()
            .into_artifact(PlanVersion { id, revision: 1 }, TurnId::new(1));
        let planning =
            apply_plan_record(PlanWorkflowState::Idle, &PlanRecord::Started { id }).unwrap();
        assert!(
            apply_plan_record(
                planning.clone(),
                &PlanRecord::Ready {
                    artifact: artifact.clone()
                }
            )
            .is_err()
        );
        assert!(
            apply_plan_record(
                planning.clone(),
                &PlanRecord::Published {
                    artifact: artifact.clone(),
                    provenance: PlanPublicationProvenance::Synthesized,
                }
            )
            .is_err()
        );
        let worker_id = AgentRunId::new();
        let provenance = PlanPublicationProvenance::ConfirmedWorker {
            run_id: EnsembleRunId::new(),
            worker_id: worker_id.clone(),
            revision: WorkerPlanRevision {
                worker_id,
                generation: 1,
                revision: 1,
                digest: "cross-record validation owns the receipt".into(),
            },
        };
        let record = PlanRecord::Published {
            artifact: artifact.clone(),
            provenance,
        };
        let restored: PlanRecord =
            serde_json::from_str(&serde_json::to_string(&record).unwrap()).unwrap();
        assert_eq!(restored, record);
        assert_eq!(
            apply_plan_record(planning.clone(), &record).unwrap(),
            PlanWorkflowState::Published { artifact }
        );
        let PlanRecord::Published {
            mut artifact,
            provenance,
        } = record
        else {
            unreachable!()
        };
        artifact.title = "Forged title".into();
        assert!(
            apply_plan_record(
                planning,
                &PlanRecord::Published {
                    artifact,
                    provenance
                }
            )
            .is_err()
        );
    }

    #[test]
    fn replay_tracks_revision_and_resolution() {
        let id = PlanId::new();
        let first = PlanArtifact {
            version: PlanVersion { id, revision: 1 },
            title: "Durable plan workflow".to_string(),
            markdown: valid_markdown("Durable plan workflow"),
            source_turn_id: TurnId::new(1),
        };
        let records = [
            PlanRecord::Started { id },
            PlanRecord::Ready {
                artifact: first.clone(),
            },
            PlanRecord::RevisionRequested {
                artifact: first.clone(),
            },
        ];
        assert_eq!(
            replay_plan_state(&records).expect("valid replay"),
            PlanWorkflowState::Planning {
                id,
                previous: Some(first)
            }
        );
    }

    #[test]
    fn replay_allows_implementation_of_the_retained_revision() {
        let id = PlanId::new();
        let artifact = PlanArtifact {
            version: PlanVersion { id, revision: 1 },
            title: "Durable plan workflow".to_string(),
            markdown: valid_markdown("Durable plan workflow"),
            source_turn_id: TurnId::new(1),
        };
        let records = [
            PlanRecord::Started { id },
            PlanRecord::Ready {
                artifact: artifact.clone(),
            },
            PlanRecord::RevisionRequested {
                artifact: artifact.clone(),
            },
            PlanRecord::Resolved {
                id,
                artifact: Some(artifact.clone()),
                resolution: PlanResolution::ImplementedFresh,
            },
        ];

        assert_eq!(
            replay_plan_state(&records).expect("retained artifact should resolve"),
            PlanWorkflowState::Resolved {
                artifact,
                resolution: PlanResolution::ImplementedFresh,
            }
        );
    }
}
